# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171122_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Tagi',
            new_name='tags',
        ),
    ]
