# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Del vsebine', 'verbose_name_plural': 'Deli vsebine'},
        ),
        migrations.AddField(
            model_name='section',
            name='html_id',
            field=models.CharField(default='html_id', max_length=40, verbose_name='Navigacija za Html'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Naslov'),
        ),
    ]
