# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 20:40
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_auto_20171121_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Vsebina'),
        ),
    ]
