# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.CharField(max_length=260, verbose_name='Email naročnika')),
                ('status', models.CharField(max_length=50, verbose_name='Status naročila')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Čas prejema naročila')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Količina')),
                ('comment', models.CharField(max_length=500, verbose_name='Opomba')),
            ],
            options={
                'verbose_name': 'naročilo',
                'verbose_name_plural': 'naročila',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Ime izdelka')),
                ('img', models.ImageField(upload_to='', verbose_name='Fotografija')),
                ('size', models.CharField(blank=True, max_length=20, null=True, verbose_name='Velikost/količina')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cena v €')),
                ('sold', models.BooleanField(default=False, verbose_name='Prodano')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Opis izdelka')),
            ],
            options={
                'verbose_name': 'Izdelek',
                'verbose_name_plural': 'Izdelki',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Product', verbose_name='Za izdelek:'),
        ),
    ]
