# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Opis izdelka'),
        ),
    ]
