# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20171121_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='month_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Vzdrževanje na mesec v €'),
        ),
    ]
