# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 21:02
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_product_month_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Opis izdelka'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Kratek opis izdelka (max 40 znakov)'),
        ),
    ]
